services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5001:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://mongodb:27017
      - MONGODB_DATABASE_NAME=metaverse-social
      - MONGODB_USER_COLLECTION=users
      - MONGODB_SCENARIO_COLLECTION=scenarios
      - MONGODB_SESSION_COLLECTION=sessions
      - MONGODB_INTERACTION_COLLECTION=interactions

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5000:3000"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5001/api

volumes:
  mongodb_data_container:
